---

- hosts: all
  become: true
  tasks:
  - name: Install Apache and php support for apache
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
      cache_valid_time: 3600
    when: ansible_os_family == "Debian"
  
  - name: zypper Update cache and Install Apache
    community.general.zypper:
      name:
        - apache2
        - apache2-mod_php8
      state: latest
      update_cache: yes
    when: ansible_os_family == "Suse"
  

