---

- hosts: all
  become: true
  pre_tasks:
  - name: Update apt system
    tags: always
      - update
    apt:
      upgrade: dist
      update_cache: yes
      cache_valid_time: 3600
    when: ansible_os_family == "Debian"
  - name: update zypper system
    tags: always
      - update
    community.general.zypper:
      update_cache: yes
      name: '*'
      state: latest
      type: patch
    when: ansible_os_family == "Suse"

- hosts: web_servers
  become: true
  tasks:
  - name: Install Apache and php support for apache
    tags: apache,apache2,ubuntu 
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_os_family == "Debian"
  - name: zypper Update cache and Install Apache
    tags: apache,apache2,suse  
    community.general.zypper:
      name:
        - apache2
        - apache2-mod_php8
      state: latest
    when: ansible_os_family == "Suse"
  
  - name: Copy default site to web server ubuntu
    tags: apache,apache2,ubuntu
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: '0644'
    when: ansible_os_family == "Debian"

  - name: Copy default site to web server suse
    tags: apache,apache2,suse
    copy:
      src: default_site.html
      dest: /srv/www/htdocs/index.html
      owner: root
      group: root
      mode: '0644'
    when: ansible_os_family == "Suse"

  
- hosts: db_servers
  become: true
  tasks:
  - name: apt Install MariaDB server
    tags: mariadb,db,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_os_family == "Debian"
  - name: zypper Install MariaDB server
    tags: mariadb,db,suse
    community.general.zypper:
      name: mariadb-server
      state: latest
    when: ansible_os_family == "Suse"

- hosts: file_servers
  tags: samba,fileserver
  become: true
  tasks:
  - name: Install Samba server
    package:
      name: samba
      state: latest
    